# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "CLI to check the lunch menu for this week at Bold Commerce."
  homepage "https://lunch.email/"
  version "0.1.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/game-of-morgan/lunch/releases/download/v0.1.5/lunch_0.1.5_Darwin_x86_64.tar.gz"
    sha256 "e0a079026579bd970a15de9cdc69090973689e4db00e00547a68b8de1dfe3f3a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/game-of-morgan/lunch/releases/download/v0.1.5/lunch_0.1.5_Linux_x86_64.tar.gz"
      sha256 "56dc69a37de22bcd4725ea34592cca892ad2e18cd1b6c65b769edea9133191ca"
    end
  end

  def install
    bin.install "lunch"
  end
end
