# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "CLI to check the lunch menu for this week at Bold Commerce."
  homepage "https://lunch.email/"
  version "0.1.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/game-of-morgan/lunch/releases/download/v0.1.4/lunch_0.1.4_Darwin_x86_64.tar.gz"
    sha256 "40483e468e2688471a46e71cdc480e46c526a5a630d8d4364f58e542c78a9da1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/game-of-morgan/lunch/releases/download/v0.1.4/lunch_0.1.4_Linux_x86_64.tar.gz"
      sha256 "d5c6f7bc88df94558ab3a201d8d1d80c947dd968c463c20105956150ea990b2d"
    end
  end

  def install
    bin.install "lunch"
  end
end
