# This file was generated by GoReleaser. DO NOT EDIT.
class Lunch < Formula
  desc "CLI to check the lunch menu for this week at Bold Commerce."
  homepage "https://lunch.email/"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/game-of-morgan/lunch/releases/download/v0.1.3/lunch_0.1.3_Darwin_x86_64.tar.gz"
    sha256 "1d24e628c8f5fb63d19bf429dbef6c2231d2c0763e4966ed9ca623a8a5f46e34"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/game-of-morgan/lunch/releases/download/v0.1.3/lunch_0.1.3_Linux_x86_64.tar.gz"
      sha256 "4b4f167ed75b6d5fe09ab05f568f174c9b3d92b8edbabcef4ba2e96f54e1f1a7"
    end
  end

  def install
    bin.install "lunch"
  end
end
