# This file was generated by GoReleaser. DO NOT EDIT.
class Lunch < Formula
  desc "CLI to check the lunch menu for this week at Bold Commerce."
  homepage "https://lunch.email/"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/game-of-morgan/lunch/releases/download/v0.1.2/lunch_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "4493f4dd7d77af54a577f2c004ed84af6bcc82eef4ab34964ca94050d2604f00"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/game-of-morgan/lunch/releases/download/v0.1.2/lunch_0.1.2_Linux_x86_64.tar.gz"
      sha256 "6ecae671ec4f15ee9f85774b0e59a1096e968c87dbf586c7277aeb6ca6ad4af3"
    end
  end

  def install
    bin.install "lunch"
  end
end
